runtime:
  default_interval_seconds: 300
  sleep_seconds: 0
  dry_run: false

jobs:
  - name: failed_signins
    query: |
      sqldb_database_wait_stats
      | take 5
      | project sample_time_utc, subscription_id, database_name, wait_type
    interval_seconds: 60
    nodes:
      - types:
          - Wait
        template_hashes:
          - wait-v1
        update_policy: merge
        expiration_time_min: 45
        static_properties:
          source_system: adx
          category: identity
        column_properties:
          name: wait_type
          database_name: database_name
        property_transforms:
          - property: database_name
            process:
              - type: TO_UPPER
      
      - types:
          - SUB
        template_hashes:
          - sub-v2
        update_policy: merge_at_change
        static_properties:
          source_system: adx
          category: identity
          type: subscription
        column_properties:
          name: subscription_id


    relationships:
      - type: LIVES_IN
        template_hash: user-authenticated-from-ip-v1
        update_policy: merge
        expiration_time_min: 20
        static_properties:
          source_system: adx
        column_properties:
          data_connection_source: database_name
        property_transforms:
          - property: data_connection_source
            process:
              - type: TO_LOWER
        source:
          type: Wait
          match_attributes:
            columns:
              name: wait_type
        target:
          type: SUB
          match_attributes:
            columns:
              name: subscription_id
