from __future__ import annotations

AUTO_FIELD_PREFIX = "z4j_"

NODE_UID_PROPERTY = f"{AUTO_FIELD_PREFIX}node_uid"
REL_UID_PROPERTY = f"{AUTO_FIELD_PREFIX}rel_uid"
ORIGIN_PROPERTY = f"{AUTO_FIELD_PREFIX}origin"
CREATED_AT_PROPERTY = f"{AUTO_FIELD_PREFIX}created_at"
UPDATED_AT_PROPERTY = f"{AUTO_FIELD_PREFIX}updated_at"
EXPIRES_AT_PROPERTY = f"{AUTO_FIELD_PREFIX}expires_at"
NODE_TEMPLATE_HASHES_PROPERTY = f"{AUTO_FIELD_PREFIX}template_hashes"
REL_TEMPLATE_HASH_PROPERTY = f"{AUTO_FIELD_PREFIX}template_hash"
